let potato = "potato";
console.log (typeof potato);    
// Prediction: Vegetable
// Actual: String
let myNuber = 15;
console.log (typeof myNuber);
// Prediction: Number
// Actual: String
 let Number = 5.5
console.log (typeof Number);
// Prediction: Boolean
// Actual: Boolean
 let nan = NaN;  
 console.log (typeof nan);

// Prediction: Object
 // Actual: Object
let hello = 'hello';
 // Prediction:
  // Actual:
let Nameofspaceshuttle = 'Determination';
console.log (Nameofspaceshuttle);
let shuttespeedmph =17000;
console.log (shuttespeedmph);
let DistancetoMarskm =225000000;
console.log (DistancetoMarskm);
let DistancetoMoon1 =384400;
console.log (DistancetoMoon1);
let mileperkilomtar =0.621;

let test = mileperkilomtar*DistancetoMarskm;
console.log (test);
let tesr =`$[Nameofspaceshuttle\DistancetoMoon1]`










